Solve createGetter task
js-tasks-ru/js-20220111_maksim24 pull request #3
Opened 2022-01-28 19:07 UTC by maksym-arturIn

2022-01-28 19:08 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-01 15:45 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const propsArray = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-02-01 15:45 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for (let prop of propsArray) {
`const prop`

2022-02-01 15:45 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2023-06-12 08:21 UTC, closed without merging